spring:
  sql:
    init:
      mode: always
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5432/polardb_catalog
    hikari:
      maximum-pool-size: 5
      connection-timeout: 2000
